# ─────────────────────────────────────────────────────────────────────────────
# DAP-seq pipeline configuration
# ─────────────────────────────────────────────────────────────────────────────

samples:
  TF1:
    r1: /project/zhuzhuzhang/nick/projects/dap_practice/dap_sample_data/RO-GY-2s-pl2-Zhuzhu-ampDAP-Mouse-MRKN03_S36_L004_R1_001.fastq.gz
    r2: /project/zhuzhuzhang/nick/projects/dap_practice/dap_sample_data/RO-GY-2s-pl2-Zhuzhu-ampDAP-Mouse-MRKN03_S36_L004_R2_001.fastq.gz
  TF2:
    r1: /project/zhuzhuzhang/nick/projects/dap_practice/dap_sample_data/RO-GY-2s-pl2-Zhuzhu-ampDAP-Mouse-TGIF02_S34_L004_R1_001.fastq.gz
    r2: /project/zhuzhuzhang/nick/projects/dap_practice/dap_sample_data/RO-GY-2s-pl2-Zhuzhu-ampDAP-Mouse-TGIF02_S34_L004_R2_001.fastq.gz
  input_DNA:
    r1: null
    r2: null

# Input/control sample name — must match a key in samples above.
# Remove this line or set to null to run without a control.
input_control: null

# ── Genome ───────────────────────────────────────────────────────────────────
genome_ref:   "/project/zhuzhuzhang/reference/Mouse/GRCm38/Mus_musculus.GRCm38.dna.primary_assembly.fa"
genome_dir:   "/project/zhuzhuzhang/reference/Mouse/GRCm38/"
genome_size:  "2913022398"

# ── Compute ──────────────────────────────────────────────────────────────────
threads: 8

# ── SLURM ────────────────────────────────────────────────────────────────────
slurm_partition: "caslake"
slurm_account:   "pi-zhuzhuzhang"
